#!/bin/bash

set -e
DIR=/bin

CURRENTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
INSTALLPATH_SFDX=$DIR/sfdx
$SUDO cp $CURRENTDIR/bin/sfdx $INSTALLPATH_SFDX
# Account for user mask
$SUDO chmod 755 $INSTALLPATH_SFDX

rm -rf ~/.local/share/sfdx/cli
mkdir -p ~/.local/share/sfdx
cp -r $CURRENTDIR ~/.local/share/sfdx/cli

printf "\e[0msfdx installed to \e[38;5;104m$INSTALLPATH_SFDX\e[0m\n"
$INSTALLPATH_SFDX version
